services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./node-00-web/config/nginx.conf:/etc/nginx/nginx.conf
      - ./node-00-web/config/conf.d/:/etc/nginx/conf.d/
