services:
  web:
    image: ubuntu:noble
    ports:
      - "8080:80"
    volumes:
      - ./node-00-web/web/:/var/www/html/
      - ./node-00-web/config/:/etc/nginx/
      - ./node-00-web/setup.sh:/root/setup.sh
    working_dir: /root/
    command: > 
      bash ./setup.sh